type: object
title: Action
minProperties: 1
maxProperties: 1
description: "Action represents an action that can be performed on a website. It should have a non-null value exactly one property."
properties:
  tab_close:
    type: boolean
  tab_close_all:
    type: boolean
  tab_open:
    type: boolean
  tab_duplicate:
    type: boolean
  tab_next:
    type: boolean
  tab_previous:
    type: boolean
  go_forward:
    type: boolean
  go_backward:
    type: boolean
  reload:
    type: boolean
  javascript_run:
    type: object
    properties:
      description:
        type: string
      code:
        type: string
    required:
      - code
  url_copy:
    type: boolean
  scroll_top:
    type: boolean
  scroll_bottom:
    type: boolean
  open_url:
    title: OpenURLAction
    type: object
    properties:
      url:
        type: string
      title:
        type: string
      new_tab:
        type: boolean
    required:
      - url
      - new_tab
      - title
  share:
    type: boolean
